src/Entity/Gite.php
<?php

namespace App\Entity;

use App\Repository\GiteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GiteRepository::class)]
class Gite
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?float $surface = null;

    #[ORM\Column]
    private ?int $nb_chambres = null;

    #[ORM\Column]
    private ?int $nb_lits = null;

    #[ORM\Column]
    private ?bool $accept_animaux = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $tarif_animaux = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $image = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ville $ville = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Proprietaire $proprietaire = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Contact $contact = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Prix $prix = null;

    #[ORM\ManyToMany(targetEntity: Service::class)]
    private Collection $service;

    #[ORM\ManyToMany(targetEntity: EquipementInterieur::class)]
    private Collection $equipement_interieur;

    #[ORM\ManyToMany(targetEntity: EquipementExterieur::class)]
    private Collection $equipement_exterieur;

    public function __construct()
    {
        $this->service = new ArrayCollection();
        $this->equipement_interieur = new ArrayCollection();
        $this->equipement_exterieur = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getSurface(): ?float
    {
        return $this->surface;
    }

    public function setSurface(float $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getNbChambres(): ?int
    {
        return $this->nb_chambres;
    }

    public function setNbChambres(int $nb_chambres): self
    {
        $this->nb_chambres = $nb_chambres;

        return $this;
    }

    public function getNbLits(): ?int
    {
        return $this->nb_lits;
    }

    public function setNbLits(int $nb_lits): self
    {
        $this->nb_lits = $nb_lits;

        return $this;
    }

    public function isAcceptAnimaux(): ?bool
    {
        return $this->accept_animaux;
    }

    public function setAcceptAnimaux(bool $accept_animaux): self
    {
        $this->accept_animaux = $accept_animaux;

        return $this;
    }

    public function getTarifAnimaux(): ?string
    {
        return $this->tarif_animaux;
    }

    public function setTarifAnimaux(?string $tarif_animaux): self
    {
        $this->tarif_animaux = $tarif_animaux;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getVille(): ?Ville
    {
        return $this->ville;
    }

    public function setVille(?Ville $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getProprietaire(): ?Proprietaire
    {
        return $this->proprietaire;
    }

    public function setProprietaire(?Proprietaire $proprietaire): self
    {
        $this->proprietaire = $proprietaire;

        return $this;
    }

    public function getContact(): ?Contact
    {
        return $this->contact;
    }

    public function setContact(?Contact $contact): self
    {
        $this->contact = $contact;

        return $this;
    }

    public function getPrix(): ?Prix
    {
        return $this->prix;
    }

    public function setPrix(?Prix $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getService(): Collection
    {
        return $this->service;
    }

    public function addService(Service $service): self
    {
        if (!$this->service->contains($service)) {
            $this->service->add($service);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        $this->service->removeElement($service);

        return $this;
    }

    /**
     * @return Collection<int, EquipementInterieur>
     */
    public function getEquipementInterieur(): Collection
    {
        return $this->equipement_interieur;
    }

    public function addEquipementInterieur(EquipementInterieur $equipementInterieur): self
    {
        if (!$this->equipement_interieur->contains($equipementInterieur)) {
            $this->equipement_interieur->add($equipementInterieur);
        }

        return $this;
    }

    public function removeEquipementInterieur(EquipementInterieur $equipementInterieur): self
    {
        $this->equipement_interieur->removeElement($equipementInterieur);

        return $this;
    }

    /**
     * @return Collection<int, EquipementExterieur>
     */
    public function getEquipementExterieur(): Collection
    {
        return $this->equipement_exterieur;
    }

    public function addEquipementExterieur(EquipementExterieur $equipementExterieur): self
    {
        if (!$this->equipement_exterieur->contains($equipementExterieur)) {
            $this->equipement_exterieur->add($equipementExterieur);
        }

        return $this;
    }

    public function removeEquipementExterieur(EquipementExterieur $equipementExterieur): self
    {
        $this->equipement_exterieur->removeElement($equipementExterieur);

        return $this;
    }
}

src/Controller/GiteController.php
<?php

namespace App\Controller;

use App\Entity\Gite;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class GiteController extends AbstractController
{
    #[Route('/gite/{id}', name: 'show_gite')]
    public function show(EntityManagerInterface $em, int $id): Response
    {
        $gite = $em->getRepository(Gite::class)->find($id);
        return $this->render('gite/show.html.twig',['gite' => $gite]);
    }
}

templates/gite/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{gite.nom}}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{asset('css/gite_show.css')}}">
{% endblock stylesheets %}

{% block body %}
    <div class="d-flex justify-content-center align-items-center flex-column">
        <div class="d-flex align-items-end mb-20 mt-20">
            <h2 class="mr-10">{{gite.nom}}</h2>
            <span>-</span>
            <p class="ml-10">{{gite.ville.nom}}, {{gite.ville.departement.nom}}, {{gite.ville.departement.region.nom}}</p>
        </div>
        <div class="show-gite-container d-flex ">
            <img class="gite-photo mr-10" src="{{gite.image}}" alt="photo du gite">
            <div class="info-container d-flex flex-column align-items-start">
                <button class="mt-10 mb-20 btn btn-primary absolute">Reserver</button>
                <p class="mb-50"><span>{{gite.prix}}€</span> pour le séjour</p>
                <div class="d-flex">
                    <p></p>
                </div>

                {# ANIMAUX #}
                {% if gite.acceptAnimaux %}
                    <div class="d-flex mb-10 font-600">
                        <i class="fa-solid fa-paw"></i>
                        <p class="mr-5 ml-5">Animaux accepté</p>
                        <i class="fa-solid fa-check ok"></i>
                    </div>
                    <p class="mb-50  pl-5"> {{gite.tarifAnimaux}}€ par animal </p>
                    {% else %}
                    <div class="d-flex mb-20">
                        <i class="fa-solid fa-paw"></i>
                        <p class="mr-5 ml-5 mb-50">Animaux refusé <i class="fa-solid fa-xmark notok"></i></p>
                        
                    </div>
                {% endif %}

                {# CHAMBRE ET SURFACE #}
                <div class="d-flex mb-10 font-600">
                    <i class="fa-solid fa-bed mr-5"></i>
                    <p>{{gite.nBchambres}} chambres</p>
                </div>
                <p class="mb-10 pl-5">{{gite.nbLits}} lits disponible</p>
                <p class="mb-50  pl-5">{{gite.surface}} metres habitables</p>

                {# A CONTACTER #}
                <p class="mb-5 font-600">A contacter:</p>
                <p class="mb-5  pl-5">{{gite.contact.nom}} {{gite.contact.prenom}}</p>
                <p class="mb-5  pl-5">{{gite.contact.adresse}}</p>
                <p class="mb-50  pl-5">{{gite.contact.telephone}}</p>

                {# PROPRIETAIRE #}
                <p class="mb-5 font-600">Proprietaire:</p>
                <p class="mb-5  pl-5">{{gite.proprietaire.nom}} {{gite.proprietaire.prenom}}</p>
                <p class="mb-5  pl-5">{{gite.proprietaire.adresse}}</p>
                <p class="mb-50  pl-5">{{gite.proprietaire.telephone}}</p>
            </div>
        </div>
        <div class="d-flex align-items-start mb-10 multiples">
            {# SERVICE #}
            <div class="d-flex flex-column mr-20 ml-20">
                <p class="mb-5 font-600">Service:</p>
            <ul>
                {% for service in gite.service %}
                    <li class="mb-5 pl-5">- {{service.nom}}</li>
                {% endfor %}    
            </ul>
            </div>

            {# EQUIPEMENT INTERIEUR #}
            <div class="d-flex flex-column mr-20">
                <p class="mb-5 font-600">Equipements intérieurs:</p>
                <ul>
                    {% for interieur in gite.equipementInterieur %}
                        <li class="mb-5 pl-5">- {{interieur.nom}}</li>
                    {% endfor %}
                </ul>
            </div>

            {# EQUIPEMENT EXTERIEUR #}
            <div class="d-flex flex-column">
                <p class="mb-5 font-600">Equipements extérieurs:</p>
                <ul>
                    {% for exterieur in gite.equipementExterieur %}
                        <li class="mb-5 pl-5">- {{exterieur.nom}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}